<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <IsPackable>false</IsPackable>
    <Description>Generate VDX font specimen diagrams.</Description>
    <Copyright>Copyright ©  2015</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net452" PrivateAssets="all" />
    <ProjectReference Include="..\VisioAutomation.VDX\VisioAutomation.VDX.csproj" />
  </ItemGroup>
</Project>
